language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run travis
  - npm run test -- --coverage # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: react-backend/client/build
  on:
    branch: master
